services:
  sisreg-bot:
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    volumes:
      - bot-data:/app/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - default
      - easypanel
    restart: unless-stopped
volumes:
  bot-data:
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.250.0/24
  easypanel:
    external: true
